library(data.table)
library(ggplot2)

type1.prob <- 0.8

type1.lambda <- c(1, 1, 2, 2, 3,  3, 3, 3, 4, 4,  4, 4, 3, 2, 1)
type2.lambda <- c(0, 0, 0, 1, 1,  2, 2, 2, 2, 2,  1, 1, 1, 0, 0)

env.mult <- 0.1
test.prob <- 0.1


simulate_one_day <- function(infected1, test.prob, env.mult) {
  
  # With given lambda, how many new infections would each of the currently
  # infected generate.
  new_infected1 <- mapply(function(i, j) sum(rpois(i, j)), infected$type1, env.mult * type1.lambda)
  
  # With given test probability, how many of those that were infected
  # i days ago, are tested today.
  new_tested1 <- sapply(infected$type1, function(i) rbinom(1, i, test.prob))
  infected$type1 <- infected$type1 - new_tested1
  
  # New infections generated by the type2 list
  new_infected2 <-  mapply(function(i, j) sum(rpois(i, j)), infected$type2, env.mult * type2.lambda)

  # These are all of the new infections
  total.infected <- sum(new_infected1) + sum(new_infected2)
  
  # Some of these are type1, others type2
  new_infected.type1 <- rbinom(1, total.infected, type1.prob)
  new_infected.type2 <- total.infected - new_infected.type1
  
  infected$type1 <- c(new_infected.type1, infected$type1[1:14])
  infected$type2 <- c(new_infected.type2, infected$type2[1:14])
  infected$tested <- c(sum(new_tested1), infected$tested)
  infected$infected <- c(sum(infected$type1) + sum(infected$type2), infected$infected)
  
  return (infected)
}

sims <- c()

for (j in 1:100) {
infected <- list(
  type1 = c(1, rep(0, 14)),
  type2 = rep(0, 15),
  tested = rep(0, 1),
  infected = rep(0, 1)
)

for (i in 1:90) {
  infected <- simulate_one_day(infected, test.prob=0.1, env.mult=0.1)
}
sims <- cbind(sims, infected$tested)
# infected
}


for (i in 1:60) {
  infected <- simulate_one_day(infected, test.prob=0.2, env.mult=0.01)
}
infected
for (i in 1:60) {
  infected <- simulate_one_day(infected, test.prob=0.5, env.mult=0.1)
}



infected
plot(infected$tested, type="l")

sim.dt <- data.table(sims)
sim.dt[, day := .I ]
sim.long <- melt(sim.dt, id.vars="day")
ggplot(sim.long, aes(day, value, col=variable)) + geom_line()



